{
 "openapi": "3.0.3",
 "info": {
  "title": "API Endpoints",
  "description": "Service for interacting with the Fever platform.",
  "version": "0.1",
  "contact": {
   "email": "fever@fever.energy",
   "name": "Fever Energy AB",
   "url": "https://fever.energy"
  }
 },
 "servers": [
  {
   "url": "https://api.feverenergy.com"
  }
 ],
 "tags": [
  {
   "name": "insights",
   "description": "All API operations related to Insights service"
  },
  {
   "name": "capacity",
   "description": "Capacity API for allocating and reading available capacity."
  },
  {
   "name": "status",
   "description": "Status API for reading asset operational status."
  },
  {
   "name": "fever-id",
   "description": "Fever ID API for creating and fetching Fever IDs."
  },
  {
   "name": "sites",
   "description": "Sites API for creating, fetching and updating sites."
  },
  {
   "name": "assets",
   "description": "Assets API for creating, fetching and updating assets."
  }
 ],
 "paths": {
  "/beta/fever-id": {
   "post": {
    "tags": [
     "fever-id"
    ],
    "description": "Create a Fever ID. Unique within an organization and parent to sites.",
    "security": [
     {
      "clientCredentials": [
       "fever-id/write"
      ]
     }
    ],
    "operationId": "fever-id#create",
    "summary": "Create"
   },
   "get": {
    "tags": [
     "fever-id"
    ],
    "description": "List Fever IDs.",
    "security": [
     {
      "clientCredentials": [
       "fever-id/read"
      ]
     }
    ],
    "operationId": "fever-id#list",
    "summary": "List"
   }
  },
  "/beta/fever-id/{id}": {
   "get": {
    "tags": [
     "fever-id"
    ],
    "description": "Get a Fever ID.",
    "security": [
     {
      "clientCredentials": [
       "fever-id/read"
      ]
     }
    ],
    "operationId": "fever-id#get",
    "summary": "Get"
   },
   "delete": {
    "tags": [
     "fever-id"
    ],
    "description": "Delete a Fever ID.",
    "security": [
     {
      "clientCredentials": [
       "fever-id/write"
      ]
     }
    ],
    "operationId": "fever-id#delete",
    "summary": "Delete"
   }
  },
  "/beta/fever-id/{id}/restore": {
   "get": {
    "tags": [
     "fever-id"
    ],
    "description": "Restore a previously deleted Fever ID.",
    "security": [
     {
      "clientCredentials": [
       "fever-id/write"
      ]
     }
    ],
    "operationId": "fever-id#restore",
    "summary": "Restore"
   }
  },
  "/beta/sites": {
   "post": {
    "tags": [
     "sites"
    ],
    "description": "Create a Site, child of Fever ID",
    "security": [
     {
      "clientCredentials": [
       "sites/write"
      ]
     }
    ],
    "operationId": "sites#create",
    "summary": "Create"
   },
   "get": {
    "tags": [
     "sites"
    ],
    "description": "List sites.",
    "security": [
     {
      "clientCredentials": [
       "sites/read"
      ]
     }
    ],
    "operationId": "sites#list",
    "summary": "List"
   }
  },
  "/beta/sites/{id}": {
   "get": {
    "tags": [
     "sites"
    ],
    "description": "Get a site.",
    "security": [
     {
      "clientCredentials": [
       "sites/read"
      ]
     }
    ],
    "operationId": "sites#get",
    "summary": "Get"
   },
   "patch": {
    "tags": [
     "sites"
    ],
    "description": "Update specific fields of a Site",
    "security": [
     {
      "clientCredentials": [
       "sites/write"
      ]
     }
    ],
    "operationId": "sites#update",
    "summary": "Update"
   },
   "delete": {
    "tags": [
     "sites"
    ],
    "description": "Delete a Site.",
    "security": [
     {
      "clientCredentials": [
       "sites/write"
      ]
     }
    ],
    "operationId": "sites#delete",
    "summary": "Delete"
   }
  },
  "/beta/sites/{id}/restore": {
   "get": {
    "tags": [
     "sites"
    ],
    "description": "Restore a deleted site.",
    "security": [
     {
      "clientCredentials": [
       "sites/write"
      ]
     }
    ],
    "operationId": "sites#restore",
    "summary": "Restore"
   }
  },
  "/beta/sites/{id}/readiness-check": {
   "get": {
    "tags": [
     "sites"
    ],
    "description": "Retrieve the readiness status of a specific site and details of any missing requirements to mark it as ready.",
    "security": [
     {
      "clientCredentials": [
       "sites/read"
      ]
     }
    ],
    "operationId": "sites#readiness-check",
    "summary": "Get"
   }
  },
  "/beta/sites/{id}/activate": {
   "post": {
    "tags": [
     "sites"
    ],
    "description": "Activates the specified site and its subcomponents, preparing it for Fever to assume control.",
    "security": [
     {
      "clientCredentials": [
       "sites/write"
      ]
     }
    ],
    "operationId": "sites#activate",
    "summary": "Activate"
   }
  },
  "/beta/sites/{id}/deactivate": {
   "post": {
    "tags": [
     "sites"
    ],
    "description": "Deactivates the specified site and its subcomponents, removing it from Fever's control.",
    "security": [
     {
      "clientCredentials": [
       "sites/write"
      ]
     }
    ],
    "operationId": "sites#deactivate",
    "summary": "Deactivate"
   }
  },
  "/beta/assets": {
   "post": {
    "tags": [
     "assets"
    ],
    "description": "Create a asset, child of sites",
    "security": [
     {
      "clientCredentials": [
       "assets/write"
      ]
     }
    ],
    "operationId": "assets#create",
    "summary": "Create"
   },
   "get": {
    "tags": [
     "assets"
    ],
    "description": "List assets",
    "security": [
     {
      "clientCredentials": [
       "assets/read"
      ]
     }
    ],
    "operationId": "assets#list",
    "summary": "List"
   }
  },
  "/beta/assets/{id}": {
   "get": {
    "tags": [
     "assets"
    ],
    "description": "Get a asset.",
    "security": [
     {
      "clientCredentials": [
       "assets/read"
      ]
     }
    ],
    "operationId": "assets#get",
    "summary": "Get"
   },
   "patch": {
    "tags": [
     "assets"
    ],
    "description": "Update specific fields of a Asset",
    "security": [
     {
      "clientCredentials": [
       "assets/write"
      ]
     }
    ],
    "operationId": "assets#update",
    "summary": "Update"
   },
   "delete": {
    "tags": [
     "assets"
    ],
    "description": "Delete a Asset.",
    "security": [
     {
      "clientCredentials": [
       "assets/write"
      ]
     }
    ],
    "operationId": "assets#delete",
    "summary": "Delete"
   }
  },
  "/beta/assets/{id}/restore": {
   "get": {
    "tags": [
     "assets"
    ],
    "description": "Restore a previously deleted Asset.",
    "security": [
     {
      "clientCredentials": [
       "assets/write"
      ]
     }
    ],
    "operationId": "assets#restore",
    "summary": "Restore"
   }
  },
  "/beta/assets/{id}/readiness-check": {
   "get": {
    "tags": [
     "assets"
    ],
    "description": "Retrieve the readiness status of a specific asset and details of any missing requirements to mark it as ready.",
    "security": [
     {
      "clientCredentials": [
       "assets/read"
      ]
     }
    ],
    "operationId": "assets#readiness-check",
    "summary": "Get"
   }
  },
  "/beta/assets/{id}/activate": {
   "post": {
    "tags": [
     "assets"
    ],
    "description": "Activates the specified asset, preparing it for Fever to assume control.",
    "security": [
     {
      "clientCredentials": [
       "assets/write"
      ]
     }
    ],
    "operationId": "assets#activate",
    "summary": "Activate"
   }
  },
  "/beta/assets/{id}/deactivate": {
   "post": {
    "tags": [
     "assets"
    ],
    "description": "Deactivates the specified asset, removing it from Fever's control.",
    "security": [
     {
      "clientCredentials": [
       "assets/write"
      ]
     }
    ],
    "operationId": "assets#deactivate",
    "summary": "Deactivate"
   }
  },
  "/beta/insights/earnings": {
   "get": {
    "tags": [
     "insights"
    ],
    "description": "Get net earnings for date and filter by external id's.",
    "security": [
     {
      "clientCredentials": [
       "earnings/read"
      ]
     }
    ],
    "summary": "Earnings",
    "operationId": "insights#earnings"
   }
  },
  "/beta/capacity/{external-id}/available": {
   "get": {
    "tags": [
     "capacity"
    ],
    "summary": "Get",
    "description": "Available capacity for product per hour.\nStandard: 24 entries\nDaylight savings, last Sunday in March: 23 entries\nWinter time, last Sunday in October: 25 entries\n",
    "security": [
     {
      "clientCredentials": [
       "capacity/available.read"
      ]
     }
    ],
    "operationId": "capacity#get-available"
   },
   "post": {
    "tags": [
     "capacity"
    ],
    "summary": "Create",
    "description": "Available capacity for product per hour.\nStandard: 24 entries\nDaylight savings, last Sunday in March: 23 entries\nWinter time, last Sunday in October: 25 entries\nAllowed invocation time:\n9:00-14:00 CET/CEST\n",
    "security": [
     {
      "clientCredentials": [
       "capacity/available.write"
      ]
     }
    ],
    "operationId": "capacity#post-available"
   }
  },
  "/beta/capacity/{external-id}/allocated": {
   "get": {
    "tags": [
     "capacity"
    ],
    "summary": "Get",
    "description": "Allocated capacity for product per hour.\nStandard: 24 entries\nDaylight savings, last Sunday in March: 23 entries\nWinter time, last Sunday in October: 25 entries\n",
    "security": [
     {
      "clientCredentials": [
       "capacity/allocated.read"
      ]
     }
    ],
    "operationId": "capacity#get-allocated"
   },
   "post": {
    "tags": [
     "capacity"
    ],
    "summary": "Create",
    "description": "Allocated capacity for product per hour.\nStandard: 24 entries\nDaylight savings, last Sunday in March: 23 entries\nWinter time, last Sunday in October: 25 entries\n",
    "security": [
     {
      "clientCredentials": [
       "capacity/allocated.write"
      ]
     }
    ],
    "operationId": "capacity#post-allocated"
   }
  },
  "/beta/status/{external-id}": {
   "get": {
    "tags": [
     "status"
    ],
    "summary": "Get",
    "description": "Get asset operational status",
    "security": [
     {
      "clientCredentials": [
       "asset/status.read"
      ]
     }
    ],
    "operationId": "status#get"
   }
  }
 },
 "components": {
  "securitySchemes": {
   "clientCredentials": {
    "type": "oauth2",
    "flows": {
     "clientCredentials": {
      "tokenUrl": "https://auth.feverenergy.com/oauth2/token",
      "scopes": {
       "earnings/read": "Read access to earnings.",
       "capacity/available.read": "Read access to available capacity.",
       "capacity/available.write": "Write access to available capacity.",
       "capacity/allocated.read": "Read access to allocated capacity.",
       "capacity/allocated.write": "Write access to allocated capacity.",
       "asset/status.read": "Read asset's operational status",
       "assets/write": "Write access to assets.",
       "assets/read": "Read access to assets.",
       "fever-id/read": "Read access to fever ids.",
       "fever-id/write": "Write access to fever ids.",
       "sites/read": "Read access to sites.",
       "sites/write": "Write access to sites."
      }
     }
    }
   }
  }
 }
}